/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Utils */

#ifndef _Included_jni_Utils
#define _Included_jni_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Utils
 * Method:    register
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljni/Resp;
 */
JNIEXPORT jobject JNICALL Java_jni_Utils_register
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     jni_Utils
 * Method:    login
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljni/Resp;
 */
JNIEXPORT jobject JNICALL Java_jni_Utils_login
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     jni_Utils
 * Method:    getUserInfo
 * Signature: (Ljava/lang/String;I)Ljni/User;
 */
JNIEXPORT jobject JNICALL Java_jni_Utils_getUserInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     jni_Utils
 * Method:    createRoom
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_Utils_createRoom
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     jni_Utils
 * Method:    joinRoom
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljni/Resp;
 */
JNIEXPORT jobject JNICALL Java_jni_Utils_joinRoom
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     jni_Utils
 * Method:    getRoomInfo
 * Signature: (Ljava/lang/String;I)Ljni/Room;
 */
JNIEXPORT jobject JNICALL Java_jni_Utils_getRoomInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     jni_Utils
 * Method:    getMyRooms
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_jni_Utils_getMyRooms
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
